// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl9lOFJW7nzucaXPitMRMNz2bnHHAGAUc',
    appId: '1:99829807693:web:509e9871fcf047da3cfa04',
    messagingSenderId: '99829807693',
    projectId: 'ecommerceflutter10-dba03',
    authDomain: 'ecommerceflutter10-dba03.firebaseapp.com',
    storageBucket: 'ecommerceflutter10-dba03.appspot.com',
    measurementId: 'G-M0CZ8X2FTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAreEPx6xoGZO-JOX_poX42v30xV-BTOxM',
    appId: '1:99829807693:android:87b269aecd484dbb3cfa04',
    messagingSenderId: '99829807693',
    projectId: 'ecommerceflutter10-dba03',
    storageBucket: 'ecommerceflutter10-dba03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtopG3cGAJyj6nDEm4HgdnbQznm0gX044',
    appId: '1:99829807693:ios:a12dc6a596d2c2f13cfa04',
    messagingSenderId: '99829807693',
    projectId: 'ecommerceflutter10-dba03',
    storageBucket: 'ecommerceflutter10-dba03.appspot.com',
    iosClientId: '99829807693-r5jlrduhhtpfk89j8k6bn5dboacc5j6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommercefluter10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtopG3cGAJyj6nDEm4HgdnbQznm0gX044',
    appId: '1:99829807693:ios:b0fba76c65cb7be63cfa04',
    messagingSenderId: '99829807693',
    projectId: 'ecommerceflutter10-dba03',
    storageBucket: 'ecommerceflutter10-dba03.appspot.com',
    iosClientId: '99829807693-bnvcrmfvfgscmf7gr4va66t0kus7eg6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommercefluter10.RunnerTests',
  );
}
